config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/:username', to: 'dashboard#show'
  get '/:username/repos', to: 'repos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followed.rb
class Followed
  attr_reader :login, :url

  def initialize(attributes)
    @login = attributes[:login]
    @url = attributes[:html_url]
  end
end

app/models/follower.rb
class Follower
  attr_reader :login, :url

  def initialize(attributes)
    @login = attributes[:login]
    @url = attributes[:html_url]
  end
end

app/models/git_hub_user.rb
class GitHubUser
  def initialize(current_user)
    @current_user = current_user
  end

  def repos
    ReposService.new(@current_user).repos
  end

  def starred_repos
    StarredReposService.new(@current_user).starred_repos
  end

  def following
    FollowingService.new(@current_user).following
  end

  def followers
    FollowerService.new(@current_user).followers
  end
end

app/models/profile.rb
class Profile
  attr_reader :username,
              :name
  def initialize(profile_data)
    @username = profile_data[:login]
    @name = profile_data[:name]
  end
end

app/models/repo.rb
class Repo
  attr_reader :name,
              :owner,
              :description

  def initialize(attributes)
    @name = attributes[:name]
    @owner = attributes[:owner][:login]
    @description = attributes[:description]
  end
end

app/models/starred_repo.rb
class StarredRepo
  attr_reader :name, :url

  def initialize(attributes)
    @name = attributes[:name]
    @url = attributes[:html_url]
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    user =find_or_create_by(uid: auth_info[:uid]) do | new_user |
      new_user.uid            = auth_info.extra.raw_info.id
      new_user.name           = auth_info.extra.raw_info.name
      new_user.username       = auth_info.extra.raw_info.login
      new_user.oauth_token    = auth_info.credentials.token
      new_user.avatar_url     = auth_info.extra.raw_info.avatar_url
    end
    user.update(username: auth_info.extra.raw_info.login, avatar_url: auth_info.extra.raw_info.avatar_url, oauth_token: auth_info.credentials.token)
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
   def show
    @starred_repos = GitHubUser.new(current_user).starred_repos

    @following = GitHubUser.new(current_user).following

    @followers = GitHubUser.new(current_user).followers
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @repos = GitHubUser.new(current_user).repos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to  "/#{current_user.username}"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<main class='dashboard'>
  <div class="profile">
    <img class="main-picture" src= <%="#{current_user.avatar_url}"%> alt="user picture"> <br>
    <div class="profile-text">
      <h1> <%= current_user.name %> </h1>
      <h4> <%= current_user.username %></h4>
    </div>
    <a href="/<%="#{current_user.username}"%>/repos"> Repositories</a> <br>
      <%= link_to "Logout", logout_path, method: :delete %>
  </div>

  <section class="starred">
    <h3>Starred Repos:<%= @starred_repos.count %></h3>
    <ul>
      <% @starred_repos.each do |repo| %>
      <li><%= link_to repo.name, repo.url %> </li>
      <% end %>
    </ul>
  </section>

  <section>
    <h3>Followers: <%= @followers.count %> </h3>
    <ul>
      <% @followers.each do |follower| %>
      <li><%= link_to follower.login, follower.url %> </li>
      <% end %>
    </ul>
  </section>

  <section class="following">
    <h3>Following: <%= @following.count %> </h3>
    <ul>
      <% @following.each do |follow| %>
      <li><%= link_to follow.login, follow.url %> </li>
      <% end %>
    </ul>
  </section>
</main>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="octocat-home">
    <a class="nav-thumb" href="/">
      <img class="octocat" src="https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png" >
    </a>
  </div>
    <div class="login">
      <% if current_user %>
      <%= link_to image_tag(current_user.avatar_url, class: 'user-thumbnail'), "/#{current_user.username}" %>
      <% else %>
      <%= link_to "Login With Github", github_login_path %>
      <% end %>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/repos/index.html.erb
<main class=repos-all>
  <h1> <%= current_user.username %>'s Repos </h1>

  <% @repos.each do |repo|  %>
  <div class="repo">
    <ul>
      <li> <%= repo.name %> </li>
      <li> <%= repo.owner %> </li>
      <li> <%= repo.description %> </li>
    </ul>
  </div>
  <% end %>
</main>

app/views/welcome/index.html.erb
<h1>Welcome to GitBub</h1>